version: '3.8'
services:
  rekord_postgres:
    image: postgres:15
    restart: "no"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: my_database
    command: postgres -c max_connections=10
